"""瀏覽器相關模組"""

from .ban_handler import handle_ban_decorator, parse_ban_time
from .factory import create_browser, stop_browser
from .flaresolverr import (
    FlareSolverrClient,
    FlareSolverrConfigurationError,
    FlareSolverrError,
    FlareSolverrProtocolError,
    FlareSolverrRequestError,
    FlareSolverrResult,
    FlareSolverrSession,
    FlareSolverrSessionScope,
    FlareSolverrSessionUnavailable,
    FlareSolverrSolveReceipt,
    get_flaresolverr_url,
    should_use_flaresolverr,
)
from .owner import (
    BrowserCloser,
    BrowserFactory,
    BrowserOwner,
    BrowserOwnershipError,
    BrowserOwnerState,
    BrowserOwnerStateError,
    TabBindingError,
    TabFactory,
    TabHandle,
    TabNavigator,
    TabTransport,
    TabTransportUnavailableError,
    TargetIdGetter,
)
from .process import ProcessOwnershipError

__all__ = [
    "BrowserCloser",
    "BrowserFactory",
    "BrowserOwner",
    "BrowserOwnerState",
    "BrowserOwnerStateError",
    "BrowserOwnershipError",
    "ProcessOwnershipError",
    "FlareSolverrClient",
    "FlareSolverrConfigurationError",
    "FlareSolverrError",
    "FlareSolverrProtocolError",
    "FlareSolverrRequestError",
    "FlareSolverrResult",
    "FlareSolverrSession",
    "FlareSolverrSessionScope",
    "FlareSolverrSessionUnavailable",
    "FlareSolverrSolveReceipt",
    "TabBindingError",
    "TabFactory",
    "TabHandle",
    "TabNavigator",
    "TabTransport",
    "TabTransportUnavailableError",
    "TargetIdGetter",
    "create_browser",
    "stop_browser",
    "get_flaresolverr_url",
    "handle_ban_decorator",
    "parse_ban_time",
    "should_use_flaresolverr",
]
